### ISSUE TITLE
No such file or directory vRhyme_nucmer_delta_parsed.tsv

### ISSUE THREAD

**Issue by JSSaini** [AnantharamanLab/vRhyme#2]
Hi! Thank you for providing this new tool. I tried it run it and after 30-40 seconds of job running, I am getting the following errors. I also did the prior test run and found that  "ET model: Not found". So the model --model NN was set while running the command. Please see what might be going on here? 

##test_vRhyme.py (test run)

Python Dependencies

  scikit-learn: Success (v1.0.1)
  numpy: Success (v1.20.3)
  numba: Success (v0.54.1)
  pandas: Success (v1.3.5)
  pysam: Success (v0.17.0)

  Program Dependencies

  mmseqs: Success
  samtools: Success
  prodigal: Success
  mash: Success
  nucmer: Success
  bowtie2: Success
  bwa: Success

  Machine Learning Models

  NN model: Success
  ET model: Not Found!

###Log

Command:  /home/users/s/saini7/anaconda3/envs/vRhyme/bin/vRhyme -i /home/users/s/saini7/scratch/MS2/checkv/VIBRANT_phages_Anvio.13m.S.contigs_3k/Anvio.13m.S.contigs_3k.phages_combined.fna -r /home/users/s/saini7/scratch/normalized_reads/Sample_119834/Norm_adapterQcTrimmedFiltered_Sample_119834_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119834/Norm_adapterQcTrimmedFiltered_Sample_119834_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119835/Norm_adapterQcTrimmedFiltered_Sample_119835_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119835/Norm_adapterQcTrimmedFiltered_Sample_119835_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119836/Norm_adapterQcTrimmedFiltered_Sample_119836_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119836/Norm_adapterQcTrimmedFiltered_Sample_119836_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119837/Norm_adapterQcTrimmedFiltered_Sample_119837_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119837/Norm_adapterQcTrimmedFiltered_Sample_119837_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119838/Norm_adapterQcTrimmedFiltered_Sample_119838_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119838/Norm_adapterQcTrimmedFiltered_Sample_119838_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119839/Norm_adapterQcTrimmedFiltered_Sample_119839_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119839/Norm_adapterQcTrimmedFiltered_Sample_119839_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119840/Norm_adapterQcTrimmedFiltered_Sample_119840_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119840/Norm_adapterQcTrimmedFiltered_Sample_119840_R2.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119841/Norm_adapterQcTrimmedFiltered_Sample_119841_R1.fastq /home/users/s/saini7/scratch/normalized_reads/Sample_119841/Norm_adapterQcTrimmedFiltered_Sample_119841_R2.fastq -t 16 -o vRhyme_13m --method composite --model NN

Date:     2021-12-23 (y-m-d)
Start:    10:23:33   (h:m:s)
Program:  vRhyme v1.0.0

Time (min) |  Log
--------------------------------------------------------------------
0.0           Initializing and validating vRhyme parameters
0.02          Running 'composite' dereplication: 99% identity and 20% coverage

Output errors:

```Traceback (most recent call last):
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/vRhyme", line 494, in <module>
    code, original, sequences = derep_stuff.derep_stuff_composite(in_fasta, int(threads), interest_list, folder, base, derep_len, nuc_c, nuc_b, nuc_g, nuc_split, sens1, sens2, derep_id, derep_frac, sketch_k, sketch_s, iterations)
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/derep_stuff.py", line 768, in derep_stuff_composite
    clusters_100_dict, original_seqs, coords_check = nucmer_filter_1_stuff(original_seqs, folder)
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/derep_stuff.py", line 326, in nucmer_filter_1_stuff
    with open(folder + "vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv", "r") as coords:
FileNotFoundError: [Errno 2] No such file or directory: 'vRhyme_13m/vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv'


Traceback (most recent call last):
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/vRhyme", line 494, in <module>
    code, original, sequences = derep_stuff.derep_stuff_composite(in_fasta, int(threads), interest_list, folder, base, derep_len, nuc_c, nuc_b, nuc_g, nuc_split, sens1, sens2, derep_id, derep_frac, sketch_k, sketch_s, iterations)
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/derep_stuff.py", line 768, in derep_stuff_composite
    clusters_100_dict, original_seqs, coords_check = nucmer_filter_1_stuff(original_seqs, folder)
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/derep_stuff.py", line 326, in nucmer_filter_1_stuff
    with open(folder + "vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv", "r") as coords:
FileNotFoundError: [Errno 2] No such file or directory: 'vRhyme_13m/vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv```

**Comment by JSSaini** [comment]
Update: Removing the --method flag runs the script for now.

**Comment by slambrechts** [comment]
Same here. I think it's due to the ET model not being found:

> Machine Learning Models
> 
> NN model: Success 
> ET model: Not Found!

When I check in the `vRhyme/vRhyme/models` directory, the ET model is there. However it was zipped. Unfortunately unzipping it didn't solve the problem, vRhyme was still unable to find it

**Comment by JSSaini** [comment]
@slambrechts It works by removing the --method flag and by adding  --model NN

**Comment by KrisKieft** [comment]
Hi,

Thanks for checking out vRhyme and sorry about the issues right at the start. It looks like there's probably two issues going on here. "FileNotFoundError" will occur before anything comes up with the "ET model", and you should have the ET model be "Success" so something is going on there, too.

1) My first thought for "FileNotFoundError"  is that Nucmer (or possibly Mash) is not running properly. However, you do have that program installed based on the test. Can you let me know what other files are generated in the dereplication output folder? As for the mentioned fix, that error will only occur during dereplication, so leaving `--method none` will avoid the error. Have you tried `--method longest`? 

2) How was vRhyme installed? Did you run the pip install test? Given that the NN model was found I'm not sure why the ET model was never unzipped, which should have occurred whether pip was run or not. Are you able to locate the vRhme `models` directory and run `gunzip vRhyme_machine_model_ET.sav.gz`? If not I can try to assist further with locating it. vRhyme itself also has a check to unzip the model if necessary so it may actually run on default or `--model ET` settings. 

For further verification vRhyme comes with a test set to verify that everything is working, including locating the ET model. It will just take a couple seconds to run the test.

**Comment by JSSaini** [comment]
Thank you for getting in touch. 

1. For some reason jobs does not go through using >> --method longest. And leaves the folders empty. Upon removing the --method flag everything works fine.  
2. I installed the vRhyme using conda and --model ET is not installed along according to the text run. So I am running using --model NN. I hope this information helps.

**Comment by KrisKieft** [comment]
There appears to be something specifically wrong with dereplication, which is likely with Nucmer or Mash. I haven't had a chance to verify compatible versions with those tools, so I'd suggest updating them. I run Nucmer v3.1 (the base software is Mummer) and Mash v2.3. 

Did you clone the GitHub repository and then create a conda environment? There isn't a way to install vRhyme using conda directly. The README just has information on creating an environment rather than installation through conda. If you only cloned the GitHub repository (and not pip install) then you can locate the `models` folder within the vRhyme download and manually unzip the model according to my previous message. Also, verify that you activate the conda environment before running.

Lastly, using just `--model NN` will work but the accuracy and recall of vRhyme is better with `--model hybrid`.

**Comment by JSSaini** [comment]
Thank you for the reply. Yes, Nucmer (v3.1) or Mash (v2.3) is up to date. The job still fails with --method longest. However, this time 'vRhyme_depreplication' folder generated the files but other folders (vRhyme_bam_files, vRhyme_coverage_files, vRhyme_sam_files) were empty.  

Following was the error; 
Traceback (most recent call last):
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/vRhyme", line 499, in <module>
    code, original, sequences = derep_stuff.derep_stuff_longest(in_fasta, int(threads), interest_list, folder, base, derep_len, nuc_c, nuc_b, nuc_g, nuc_split, derep_id, derep_frac, sketch_k, sketch_s, iterations)
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/derep_stuff.py", line 851, in derep_stuff_longest
    clusters_100_dict, original_seqs, _ = nucmer_filter_1_stuff(original_seqs, folder)
  File "/home/users/s/saini7/anaconda3/envs/vRhyme/bin/derep_stuff.py", line 326, in nucmer_filter_1_stuff
    with open(folder + "vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv", "r") as coords:
FileNotFoundError: [Errno 2] No such file or directory: 'vRhyme_13m/vRhyme_dereplication/vRhyme_nucmer_delta_parsed.tsv'

I cloned using the Github repository and installed it via pip as per the instructions this time. Upon extracting the ET model zip file manually, both models appeared. Following is the test run;

test_vRhyme.py

  Python Dependencies
  -------------------
  scikit-learn: Success (v1.0.1)
  numpy: Success (v1.20.3)
  numba: Success (v0.54.1)
  pandas: Success (v1.3.5)
  pysam: Success (v0.17.0)


  Program Dependencies
  --------------------
  mmseqs: Success
  samtools: Success
  prodigal: Success
  mash: Success
  nucmer: Success
  bowtie2: Success
  bwa: Success


  Machine Learning Models
  -----------------------
  NN model: Success
  ET model: Success

Thank you for your help. Why would adding --method longest would give an error and removing --method flag works fine?

**Comment by KrisKieft** [comment]
By default vRhyme has `--method none` meaning there is no dereplication step. Adding either `--method longest` or `--method composite` will run dereplication. The error is saying that one of the dereplication files isn't present (i.e., never generated), so some step of that is causing an issue. Skipping it (`--method none`) will basically bypass that issue. 

There are other mechanisms to dereplicate (e.g., dRep) that you can use if you require dereplication. After getting the ET model unzipped the actual binning function of vRhyme should work just fine. Use `--model hybrid` for best results. There is no need to run any dereplication for vRhyme.

**Comment by JSSaini** [comment]
My one metagenomic sample (one depth from a Lake) yielded 26k viral genomes while accounting for only vRhyme best bins. 
I certainly need to use the dereplication step to get representative genomes from each sample. 

Have you tried dRep on viral genomes? Does it work?

**Comment by KrisKieft** [comment]
I'm not entirely sure I understand your question. Are you saying that when using viruses predicted by VIBRANT, vRhyme generates 1.2k vMAGs. Then when using viruses predicted by deepVirFinder, vRhyme generates 26k vMAGs? I'll need to know more information about your workflow/protocol and where CheckV fits in order to better answer your question. However, in my opinion, VIBRANT and VirSorter provide the best virus prediction results. VirFinder and deepVirFinder can be decent if you have the correct thresholds set. 

Yes I have used dRep on viral genomes and have not run into any noticeable issues. Just make sure you turn off quality filtering with CheckM. There's a dRep flag to do that (`--ignoreGenomeQuality`).

**Comment by slambrechts** [comment]
> 2\. How was vRhyme installed? Did you run the pip install test? Given that the NN model was found I'm not sure why the ET model was never unzipped, which should have occurred whether pip was run or not. Are you able to locate the vRhme `models` directory and run `gunzip vRhyme_machine_model_ET.sav.gz`? If not I can try to assist further with locating it. vRhyme itself also has a check to unzip the model if necessary so it may actually run on default or `--model ET` settings.
> 
> For further verification vRhyme comes with a test set to verify that everything is working, including locating the ET model. It will just take a couple seconds to run the test.


For the installation I used the suggested method using GitHub, pip, and conda:


```
git clone https://github.com/AnantharamanLab/vRhyme
create the conda environment
activate the conda environment
cd vRhyme
pip install . ← NOTE: don't forget the dot (pip install [dot])
```

I did not continue with the test set yet, because of the `ET model: Not Found!` warning when running `test_vRhyme.py`

However, when running `aux/test_vRhyme.py` it does find the ET model:

```
Machine Learning Models
  -----------------------
  NN model: Success
  ET model: Success

```

So I will continue with the test set and report back. Thanks

**Comment by slambrechts** [comment]
So I guess the problem (at least for me) was in the conda environment, because the same thing happens with the test set:

When I activate the conda env and run `vRhyme -i example_scaffolds.fasta -c example_coverage_values.tsv -t 48`, vRhyme does not find the ET model :

```
Traceback (most recent call last):
  File "/scratch/gent/vo/000/gvo00043/vsc42339/conda/envs/vRhyme/bin/vRhyme", line 897, in <module>
    net_data = machine_stuff.machine_stuff(distances, presets, model_method, pairs_machine, cohen_machine, iterations)
  File "/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/conda/envs/vRhyme/bin/machine_stuff.py", line 71, in machine_stuff
    with open(f'{ml_path}vRhyme_machine_model_ET.sav', 'rb') as read_model_ET:
FileNotFoundError: [Errno 2] No such file or directory: '/kyukon/scratch/gent/vo/000/gvo00043/vsc42339/conda/envs/vRhyme/lib/python3.9/site-packages/vRhyme/models/vRhyme_machine_model_ET.sav'

```

This is because in the conda env there is no ET model in the `/envs/vRhyme/lib/python3.9/site-packages/vRhyme/models/` directory

When I activate the conda env and run `/scratch/gent/vo/000/gvo00043/vsc42339/vRhyme/vRhyme/vRhyme -i example_scaffolds.fasta -c example_coverage_values.tsv -t 48
`, it works, because in the github clone there is an ET model file in the models directory:


```
Command:  /scratch/gent/vo/000/gvo00043/vsc42339/vRhyme/vRhyme/vRhyme -i example_scaffolds.fasta -c example_coverage_values.tsv -t 48

Date:     2022-01-03 (y-m-d)
Start:    10:28:39   (h:m:s)
Program:  vRhyme v1.0.0


Time (min) |  Log                                                   
--------------------------------------------------------------------
0.0           Initializing and validating vRhyme parameters
              Caution: vRhyme performs optimally with 3+ samples
0.01          Performing pairwise coverage comparisons
0.02          Running Prodigal on filtered sequences
0.04          Generating codon usage features
0.04          Generating nucleotide features
0.05          Performing pairwise distance calculations
0.06          Performing machine learning classification
0.1           Generating networks of bins
0.12          Extracting information for all possible unique bins
0.12          Running mmseqs2 linclust for bin redundancy scoring
0.14          Parsing linclust protein clusters
0.14          Scoring all possible unique bins
0.14          Identifying best set of bins from 10 iterations
0.14          Extracting binning summary statistics for each iteration
0.15          Writing finalized bin sequences to individual fasta files
0.15          vRhyme binning complete

Memory usage:       0.39
Runtime (min):      0.15
Bins generated:     2
Binned sequences:   8 (66.7%)
Input sequences:    12
Binned proteins:    136
Redundant proteins: 0 (0.0%)
Best iteration:     0
vRhyme score:       0.6042


______________________________________________________________________

             ## ## ## ##                                              
             ##       ##  ##      ##     ##    ## ## ##     # ## ##   
##       ##  ##       ##  ##       ##    ##  ##   ##   ##  ##      #  
 ##     ##   ##     ##    ##         ## ##   ##   ##   ##  ## ## ##   
  ##   ##    ## ####      ## ## ##     ##    ##   ##   ##  ##         
   ## ##     ##   ##      ##    ##    ##     ##   ##   ##  ##         
    ###      ##     ##    ##    ##   ##      ##   ##   ##   ## ## ##  
______________________________________________________________________
```

Copying the ET model to the models directory of the conda environment solves the problem for me

**Comment by KrisKieft** [comment]
Conda can be finicky at times and I'm happy you were able to figure it out. From what you've said I believe the issue has been resolved and was due to the conda environment not picking up the ET model. If you have any further issues please let me know. Keep posting here if the further issues are related or open up a new Issue for anything new. Thanks!

**Comment by JSSaini** [comment]
Thank you for resolving this.
