### ISSUE TITLE
vRhyme 'incompatible dtype' in modules

### ISSUE THREAD

**Issue by cam315** [AnantharamanLab/vRhyme#23]
Dear developer,

Thanks for the nice tool. I am new to use vRhyme and found the issue with error message regarding 'incompatible dtype' as follows:

miniconda3/envs/vRhyme/bin/vRhyme:16: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Traceback (most recent call last):
  File "miniconda3/envs/vRhyme/bin/vRhyme", line 960, in <module>
    net_data = machine_stuff.machine_stuff(distances, presets, model_method, pairs_machine, cohen_machine, iterations, cohen_check)
  File "miniconda3/envs/vRhyme/bin/machine_stuff.py", line 73, in machine_stuff
    model_ET = pickle.load(read_model_ET)
  File "sklearn/tree/_tree.pyx", line 714, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn/tree/_tree.pyx", line 1418, in sklearn.tree._tree._check_node_ndarray

ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]

In my env, the versions info:
vrhyme                     1.1.0
python                   3.10.12
scikit-learn               1.3.0

Could you please help me to figure it out? Thank you.

**Comment by KrisKieft** [comment]
Hi, try installing the scikit-learn version listed in the README

**Comment by cam315** [comment]
solved. thank you
