### ISSUE TITLE
Release versions format

### ISSUE THREAD

**Issue by jayramr** [AnantharamanLab/vRhyme#9]
Hello,

Could you generate package releases as per the version number on github, so we can download as per specific versions 

Please refer. -> https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release

Thanks
Jay

**Comment by rpetit3** [comment]
Hi @KrisKieft 

I'm working with @jayramr  to make vRhyme available on Bioconda. @jayramr has done most of the legwork here: https://github.com/bioconda/bioconda-recipes/pull/35560

Was hoping we could get your help creating a versioned release to use for the Bioconda recipe. Once vRhyme is added to Bioconda, it'll also be made available as a Docker container from Biocontainers, and as a Singularity image from the Galaxy Project. The Bioconda bot will also recognize future releases and automatically update the recipe.

Let us know if we can help in any way!
Robert

**Comment by KrisKieft** [comment]
Hi,

Thanks for getting this up on bioconda. I have updated the most recent version as a release.

Kris

**Comment by rpetit3** [comment]
Awesome! Thank you very much! We'll get this added to bioconda

**Comment by rpetit3** [comment]
This has been merged in to Bioconda now. Thanks again for creating the release @KrisKieft
